app:
  port: 28083

database:
  host: postgres-payment
  port: 5432
  user: admin
  password: admin
  name: payment

redis:
  host: redis
  port: 6379
  password: admin

secret:
  jwt_secret: secret301

kafka:
  broker: localhost:9093
  topics:
    - order.created: order.created
    - payment.success: payment.success
  group_id: payment-service

xendit:
  secret_api_key: ""
  webhook_token: ""
